import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className + ' ' + {/*'lg:flex lg:flex-col hidden'*/ }}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
